version: "3"
services:
  product-db:
    image: mongo:latest
    container_name: product-db
    restart: always
    ports:
      - 27017:27017

  mysqldb-order:
    image: "mysql:5.7"
    container_name: mysqldb-order
    ports:
      - "3306:3306"
    restart: on-failure
    environment:
      MYSQL_HOST: mysqldb-order
      MYSQL_USER: orderuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    healthcheck:
      test: "mysql -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SHOW DATABASES;'"
      interval: 30s
      timeout: 10s
      retries: 5

  mysqldb-inventory:
    image: "mysql:5.7"
    container_name: mysqldb-inventory
    ports:
      - "3307:3306"
    restart: on-failure
    environment:
      MYSQL_HOST: mysqldb-inventory
      MYSQL_USER: inventoryuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    healthcheck:
      test: "mysql -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SHOW DATABASES;'"
      interval: 30s
      timeout: 10s
      retries: 5

